/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Category: typeof import('./src/components/Blog/Category.vue')['default']
    Cover: typeof import('./src/components/Blog/Cover.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    Home: typeof import('./src/components/Home.vue')['default']
    Info: typeof import('./src/components/Blog/Info.vue')['default']
    Login: typeof import('./src/components/Index/Login.vue')['default']
    NoteList: typeof import('./src/components/Blog/NoteList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snow: typeof import('./src/components/Index/Snow.vue')['default']
    SnowNew: typeof import('./src/components/Index/SnowNew.vue')['default']
  }
}
